# Generated by Django 3.2.5 on 2022-06-29 17:22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('numero_paginas', models.PositiveIntegerField()),
                ('data_publicacao', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='uploads/thumbnails/')),
                ('local_publicacao', models.CharField(max_length=200)),
                ('categorias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Ação e aventura', 'Ação e aventura'), ('Ficção afro-americana', 'Ficção afro-americana'), ('Antologias', 'Antologias'), ('Infantil', 'Infantil'), ('Ficção Cristã', 'Ficção Cristã'), ('Clássicos', 'Clássicos'), ('Quadrinhos e romances gráficos', 'Quadrinhos e romances gráficos'), ('Chegando à maioridade', 'Chegando à maioridade'), ('Ficção Contemporânea', 'Ficção Contemporânea'), ('Cultural e étnico', 'Cultural e étnico'), ('Fantasia', 'Fantasia'), ('Ficção histórica', 'Ficção histórica'), ('Humor e comédia', 'Humor e comédia'), ('Ficção LGBTQ', 'Ficção LGBTQ'), ('Ficção Literária', 'Ficção Literária'), ('Mashups', 'Mashups'), ('Mistério e crime', 'Mistério e crime'), ('Peças e roteiros', 'Peças e roteiros'), ('Poesia', 'Poesia'), ('Romance', 'Romance'), ('Ficção científica', 'Ficção científica'), ('Contos', 'Contos'), ('Temáticas e motivações', 'Temáticas e motivações'), ('Thriller e Suspense', 'Thriller e Suspense'), ('Ficção Feminina', 'Ficção Feminina'), ('Jovem adulto', 'Jovem adulto'), ('Agricultura', 'Agricultura'), ('Biografias e memórias', 'Biografias e memórias'), ('Gestão de negócios', 'Gestão de negócios'), ('Guias de carreira', 'Guias de carreira'), ('Não-ficção infantil', 'Não-ficção infantil'), ('Quadrinhos não ficção', 'Quadrinhos não ficção'), ('Computadores e Internet', 'Computadores e Internet'), ('Culinár', 'Culinária, comida, vinho e bebidas espirituosas'), ('Faça você mesmo e artesanato', 'Faça você mesmo e artesanato'), ('Projeto', 'Projeto'), ('Educação e Referência', 'Educação e Referência'), ('Entretenimento', 'Entretenimento'), ('Saúde e Bem-Estar', 'Saúde e Bem-Estar'), ('Casa e jardim', 'Casa e jardim'), ('Humanidades e Ciências Sociais', 'Humanidades e Ciências Sociais'), ('Inspirador', 'Inspirador'), ('LGBTQ Não Ficção', 'LGBTQ Não Ficção'), ('Matemática e Ciências', 'Matemática e Ciências'), ('Natureza', 'Natureza'), ('Nova era', 'Nova era'), ('Paternidade e famílias', 'Paternidade e famílias'), ('Fotografia', 'Fotografia'), ('Religião e Espiritualidade', 'Religião e Espiritualidade'), ('Autoajuda e autoaprimoramento', 'Autoajuda e autoaprimoramento'), ('Sexo e Relacionamentos', 'Sexo e Relacionamentos'), ('Esportes e atividades ao ar livre', 'Esportes e atividades ao ar livre'), ('Tecnologia', 'Tecnologia'), ('Viajar por', 'Viajar por'), ('Crime Verdadeiro', 'Crime Verdadeiro'), ('Casamentos', 'Casamentos'), ('Escrita e Publicação', 'Escrita e Publicação')], max_length=100), default=list, size=None)),
                ('autores', models.ManyToManyField(blank=True, related_name='livros_autor', to='livros.Autor', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
