# Generated by Django 3.2.13 on 2022-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='visibilidade',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
