# Generated by Django 3.2.13 on 2022-07-08 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0002_livro_visibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='usuarios_favoritaram',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
